# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime


class Ui_AdminRegistration(object):
    def setupUi(self, AdminRegistration):
        AdminRegistration.setObjectName("AdminRegistration")
        AdminRegistration.resize(807, 661)
        AdminRegistration.setStyleSheet("background-color:#D9D9D9;")
        self.centralwidget = QtWidgets.QWidget(AdminRegistration)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 60, 601, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Jewell7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        font.setBold(True)
        self.Jewell7.setFont(font)
        self.Jewell7.setAlignment(QtCore.Qt.AlignCenter)
        self.Jewell7.setObjectName("Jewell7")
        self.verticalLayout.addWidget(self.Jewell7)
        self.Hardware = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        font.setBold(True)
        self.Hardware.setFont(font)
        self.Hardware.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Hardware.setAlignment(QtCore.Qt.AlignCenter)
        self.Hardware.setObjectName("Hardware")
        self.verticalLayout.addWidget(self.Hardware)
        self.firstName_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.firstName_input.setFont(font)
        self.firstName_input.setStyleSheet("background-color:#FFFFFF;")
        self.firstName_input.setText("")
        self.firstName_input.setObjectName("firstName_input")
        self.verticalLayout.addWidget(self.firstName_input)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lastName_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lastName_input.setFont(font)
        self.lastName_input.setStyleSheet("background-color:#FFFFFF;")
        self.lastName_input.setText("")
        self.lastName_input.setObjectName("lastName_input")
        self.verticalLayout.addWidget(self.lastName_input)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.username_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.username_input.setFont(font)
        self.username_input.setStyleSheet("background-color:#FFFFFF;")
        self.username_input.setText("")
        self.username_input.setObjectName("username_input")
        self.verticalLayout.addWidget(self.username_input)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.password_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.password_input.setFont(font)
        self.password_input.setStyleSheet("background-color:#FFFFFF;")
        self.password_input.setText("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.verticalLayout.addWidget(self.password_input)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.birthDate_edit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.birthDate_edit.setFont(font)
        self.birthDate_edit.setStyleSheet("background-color:#FFFFFF;")
        self.birthDate_edit.setCalendarPopup(True)
        self.birthDate_edit.setObjectName("birthDate_edit")
        self.verticalLayout.addWidget(self.birthDate_edit)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.mmaidenName_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mmaidenName_input.setFont(font)
        self.mmaidenName_input.setStyleSheet("background-color:#FFFFFF;")
        self.mmaidenName_input.setText("")
        self.mmaidenName_input.setObjectName("mmaidenName_input")
        self.verticalLayout.addWidget(self.mmaidenName_input)
        self.loa_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.loa_input.setFont(font)
        self.loa_input.setStyleSheet("background-color:#FFFFFF;")
        self.loa_input.setReadOnly(True)
        self.loa_input.setPlaceholderText("")
        self.loa_input.setObjectName("loa_input")
        self.verticalLayout.addWidget(self.loa_input)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.registerButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.registerButton.setFont(font)
        self.registerButton.setStyleSheet("background-color:#53C851;")
        self.registerButton.setDefault(True)
        self.registerButton.setFlat(False)
        self.registerButton.setObjectName("registerButton")
        # Connect the "Register" button to the register_user method
        self.registerButton.clicked.connect(self.register_user)
        self.horizontalLayout.addWidget(self.registerButton)
        self.clearButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.clearButton.setFont(font)
        self.clearButton.setStyleSheet("background-color:#E14545;\n"
"")
        self.clearButton.setDefault(True)
        self.clearButton.setObjectName("clearButton")
        # Connect the "Clear" button to the clear_text method
        self.clearButton.clicked.connect(self.clear_text)
        self.horizontalLayout.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        AdminRegistration.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AdminRegistration)
        self.statusbar.setObjectName("statusbar")
        AdminRegistration.setStatusBar(self.statusbar)

        self.retranslateUi(AdminRegistration)
        QtCore.QMetaObject.connectSlotsByName(AdminRegistration)

    def retranslateUi(self, AdminRegistration):
        _translate = QtCore.QCoreApplication.translate
        AdminRegistration.setWindowTitle(_translate("AdminRegistration", "MainWindow"))
        self.Jewell7.setText(_translate("AdminRegistration", "Jewell 7"))
        self.Hardware.setText(_translate("AdminRegistration", "Hardware"))
        self.firstName_input.setPlaceholderText(_translate("AdminRegistration", "First Name"))
        self.lastName_input.setPlaceholderText(_translate("AdminRegistration", "Last Name"))
        self.username_input.setPlaceholderText(_translate("AdminRegistration", "Username"))
        self.password_input.setPlaceholderText(_translate("AdminRegistration", "Password"))
        self.mmaidenName_input.setPlaceholderText(_translate("AdminRegistration", "Mother\'s Maiden Name:"))
        self.loa_input.setText(_translate("AdminRegistration", "Admin"))
        self.registerButton.setText(_translate("AdminRegistration", "Register"))
        self.clearButton.setText(_translate("AdminRegistration", "Clear"))

    def clear_text(self):
        self.firstName_input.clear()
        self.lastName_input.clear()
        self.username_input.clear()
        self.password_input.clear()
        self.mmaidenName_input.clear()
        self.birthDate_edit.setDate(QtCore.QDate.currentDate())
    
    def register_user(self):
        # Fetching data from input fields
        first_name = self.firstName_input.text()
        last_name = self.lastName_input.text()
        username = self.username_input.text()
        password = self.password_input.text()
        loa = self.loa_input.text()
        mother_maiden = self.mmaidenName_input.text()
        birthdate = self.birthDate_edit.date().toString(QtCore.Qt.ISODate)

        # Get the current date
        current_date = datetime.today()
        # Format the date to ISO 8601 format
        date_started = current_date.strftime('%Y-%m-%d')

        # Establishing connection with SQLite database
        conn = sqlite3.connect('j7h.db')
        cursor = conn.cursor()

        # Inserting data into the users table
        cursor.execute('''INSERT INTO users (first_name, last_name, username, password, loa) 
                  VALUES (?, ?, ?, ?, ?)''', (first_name, last_name, username, password, loa))

        # Retrieve the user_id of the newly inserted user
        user_id = cursor.lastrowid  # This fetches the last inserted row id, which is the user_id

        # Inserting data into the admin table using the retrieved user_id
        cursor.execute('''INSERT INTO admin (first_name, last_name, birthdate, date_started, mother_maiden, user_id) 
                  VALUES (?, ?, ?, ?, ?, ?)''', (first_name, last_name, birthdate, date_started, mother_maiden, user_id))

        # Committing the transaction and closing connection
        conn.commit()
        conn.close()

        # Displaying a message box
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setText("User Registered Successfully!")
        msg.setWindowTitle("Success")
        msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminRegistration = QtWidgets.QMainWindow()
    ui = Ui_AdminRegistration()
    ui.setupUi(AdminRegistration)
    AdminRegistration.show()
    sys.exit(app.exec_())
