# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ForgotPassword(object):
    def setupUi(self, ForgotPassword):
        ForgotPassword.setObjectName("ForgotPassword")
        ForgotPassword.resize(592, 481)
        self.centralwidget = QtWidgets.QWidget(ForgotPassword)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 110, 531, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.newPassword_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.newPassword_label.setFont(font)
        self.newPassword_label.setObjectName("newPassword_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.newPassword_label)
        self.confirmPassword_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.confirmPassword_label.setFont(font)
        self.confirmPassword_label.setObjectName("confirmPassword_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.confirmPassword_label)
        self.confirmPassword_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.confirmPassword_input.setFont(font)
        self.confirmPassword_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPassword_input.setObjectName("confirmPassword_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.confirmPassword_input)
        self.newPassword_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.newPassword_input.setFont(font)
        self.newPassword_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newPassword_input.setObjectName("newPassword_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.newPassword_input)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.changePassword_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.changePassword_button.setFont(font)
        self.changePassword_button.setStyleSheet("background-color:#53C851;")
        self.changePassword_button.setDefault(True)
        self.changePassword_button.setFlat(False)
        self.changePassword_button.setObjectName("changePassword_button")
        self.horizontalLayout.addWidget(self.changePassword_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        ForgotPassword.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ForgotPassword)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 592, 22))
        self.menubar.setObjectName("menubar")
        ForgotPassword.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ForgotPassword)
        self.statusbar.setObjectName("statusbar")
        ForgotPassword.setStatusBar(self.statusbar)

        self.retranslateUi(ForgotPassword)
        QtCore.QMetaObject.connectSlotsByName(ForgotPassword)

    def retranslateUi(self, ForgotPassword):
        _translate = QtCore.QCoreApplication.translate
        ForgotPassword.setWindowTitle(_translate("ForgotPassword", "MainWindow"))
        self.newPassword_label.setText(_translate("ForgotPassword", "New Password:"))
        self.confirmPassword_label.setText(_translate("ForgotPassword", "Confirm Password:"))
        self.changePassword_button.setText(_translate("ForgotPassword", "Change Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ForgotPassword = QtWidgets.QMainWindow()
    ui = Ui_ForgotPassword()
    ui.setupUi(ForgotPassword)
    ForgotPassword.show()
    sys.exit(app.exec_())
