# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Staff(object):
    def setupUi(self, Staff):
        Staff.setObjectName("Staff")
        Staff.resize(600, 700)
        Staff.setStyleSheet("background-color:#D9D9D9;")
        self.centralwidget = QtWidgets.QWidget(Staff)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(10, 10, 121, 20))
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(180, 60, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(170, 120, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.lineEdit1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit1.setGeometry(QtCore.QRect(120, 210, 351, 40))
        self.lineEdit1.setStyleSheet("background-color:#FFFFFF;")
        self.lineEdit1.setText("")
        self.lineEdit1.setObjectName("lineEdit1")
        self.lineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit2.setGeometry(QtCore.QRect(120, 270, 351, 40))
        self.lineEdit2.setStyleSheet("background-color:#FFFFFF;")
        self.lineEdit2.setText("")
        self.lineEdit2.setObjectName("lineEdit2")
        self.lineEdit3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit3.setGeometry(QtCore.QRect(120, 330, 351, 40))
        self.lineEdit3.setStyleSheet("background-color:#FFFFFF;")
        self.lineEdit3.setText("")
        self.lineEdit3.setObjectName("lineEdit3")
        self.lineEdit4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit4.setGeometry(QtCore.QRect(120, 390, 351, 40))
        self.lineEdit4.setStyleSheet("background-color:#FFFFFF;")
        self.lineEdit4.setText("")
        self.lineEdit4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit4.setObjectName("lineEdit4")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(140, 525, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton1.setFont(font)
        self.pushButton1.setStyleSheet("background-color:#53C851;")
        self.pushButton1.setDefault(True)
        self.pushButton1.setFlat(False)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(310, 525, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton2.setFont(font)
        self.pushButton2.setStyleSheet("background-color:#E14545;")
        self.pushButton2.setDefault(True)
        self.pushButton2.setObjectName("pushButton2")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(120, 450, 351, 40))
        self.dateEdit.setStyleSheet("background-color:#FFFFFF;")
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        Staff.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Staff)
        self.statusbar.setObjectName("statusbar")
        Staff.setStatusBar(self.statusbar)

        self.retranslateUi(Staff)
        QtCore.QMetaObject.connectSlotsByName(Staff)

        # Connect the "Clear" button to the clear_text method
        self.pushButton2.clicked.connect(self.clear_text)

    def retranslateUi(self, Staff):
        _translate = QtCore.QCoreApplication.translate
        Staff.setWindowTitle(_translate("Staff", "Staff Registration"))
        self.label2.setText(_translate("Staff", "   Jewell 7 "))
        self.label3.setText(_translate("Staff", "  Hardware"))
        self.lineEdit1.setPlaceholderText(_translate("Staff", "First Name:"))
        self.lineEdit2.setPlaceholderText(_translate("Staff", "Middle Name:"))
        self.lineEdit3.setPlaceholderText(_translate("Staff", "Surname:"))
        self.lineEdit4.setPlaceholderText(_translate("Staff", "Password:"))
        self.pushButton1.setText(_translate("Staff", "Register"))
        self.pushButton2.setText(_translate("Staff", "Clear"))

    def clear_text(self):
        self.lineEdit1.clear()
        self.lineEdit2.clear()
        self.lineEdit3.clear()
        self.lineEdit4.clear()
        self.dateEdit.setDate(QtCore.QDate.currentDate())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Staff = QtWidgets.QMainWindow()
    ui = Ui_Staff()
    ui.setupUi(Staff)
    Staff.show()
    sys.exit(app.exec_())
