# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StaffOrAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from register import Ui_ProductManagement
from Staff import Ui_Staff
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):

    
    
    def openStaff(self):
        self.openStaff = QtWidgets.QMainWindow()
        self.ui = Ui_Staff()
        self.ui.setupUi(self.openStaff)
        self.Registration.hide()
        self.openStaff.show()
    
    def openAdmin(self):
        self.openAdmin = QtWidgets.QMainWindow()
        self.ui = Ui_ProductManagement()
        self.ui.setupUi(self.openAdmin)
        self.Registration.hide()
        self.openAdmin.show()




    def setupUi(self, Registration, previous_window=None):
        self.Registration = Registration  # Store the Registration instance
        self.previous_window = previous_window  # Store the reference to the previous window
        Registration.setObjectName("Registration")
        Registration.resize(500, 400)
        Registration.setStyleSheet("background-color:#D9D9D9;")
        self.label3 = QtWidgets.QLabel(Registration)
        self.label3.setGeometry(QtCore.QRect(130, 110, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.label2 = QtWidgets.QLabel(Registration)
        self.label2.setGeometry(QtCore.QRect(140, 50, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.StaffBtn = QtWidgets.QPushButton(Registration)
        self.StaffBtn.setGeometry(QtCore.QRect(80, 200, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.StaffBtn.setFont(font)
        self.StaffBtn.setStyleSheet("background-color:#53C851;")
        self.StaffBtn.setDefault(True)
        self.StaffBtn.setFlat(False)
        self.StaffBtn.setObjectName("LoginBtn")
        self.Adminbtn = QtWidgets.QPushButton(Registration)
        self.Adminbtn.setGeometry(QtCore.QRect(80, 270, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Adminbtn.setFont(font)
        self.Adminbtn.setStyleSheet("background-color:#03b1fc;")
        self.Adminbtn.setDefault(True)
        self.Adminbtn.setFlat(False)
        self.Adminbtn.setObjectName("registerbtn")
        self.pushButton = QtWidgets.QPushButton(Registration)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton.setStyleSheet("background-color:#D9D9D9;")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

         # Connect the "Staff" button to the open_staff_registration method
        self.StaffBtn.clicked.connect(self.openStaff)
        self.Adminbtn.clicked.connect(self.openAdmin)
        self.pushButton.clicked.connect(self.go_back)


       

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Dialog"))
        self.label3.setText(_translate("Registration", "  Hardware"))
        self.label2.setText(_translate("Registration", "   Jewell 7 "))
        self.StaffBtn.setText(_translate("Registration", "Staff"))
        self.Adminbtn.setText(_translate("Registration", "Admin"))
        self.pushButton.setText(_translate("Registration", "⇐"))

    def go_back(self):
        if self.previous_window:
            self.previous_window.show()
        self.Registration.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Registration = QtWidgets.QDialog()
    ui = Ui_Registration()
    ui.setupUi(Registration)
    Registration.show()
    sys.exit(app.exec_())
