import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime

class Ui_AdminRegistration(object):
    def setupUi(self, AdminRegistration):
        AdminRegistration.setObjectName("AdminRegistration")
        AdminRegistration.resize(816, 715)
        AdminRegistration.setStyleSheet("background-color:#D9D9D9;")
        self.centralwidget = QtWidgets.QWidget(AdminRegistration)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 60, 601, 585))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Jewell7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        font.setBold(True)
        self.Jewell7.setFont(font)
        self.Jewell7.setAlignment(QtCore.Qt.AlignCenter)
        self.Jewell7.setObjectName("Jewell7")
        self.verticalLayout.addWidget(self.Jewell7)
        self.Hardware = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        font.setBold(True)
        self.Hardware.setFont(font)
        self.Hardware.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Hardware.setAlignment(QtCore.Qt.AlignCenter)
        self.Hardware.setObjectName("Hardware")
        self.verticalLayout.addWidget(self.Hardware)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.firstName_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.firstName_label.setFont(font)
        self.firstName_label.setObjectName("firstName_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.firstName_label)
        self.firstName_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.firstName_input.setFont(font)
        self.firstName_input.setStyleSheet("background-color:#FFFFFF;")
        self.firstName_input.setText("")
        self.firstName_input.setPlaceholderText("")
        self.firstName_input.setObjectName("firstName_input")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.firstName_input)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.middleName_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.middleName_label.setFont(font)
        self.middleName_label.setObjectName("middleName_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.middleName_label)
        self.middleName_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.middleName_input.setFont(font)
        self.middleName_input.setStyleSheet("background-color:#FFFFFF;")
        self.middleName_input.setText("")
        self.middleName_input.setPlaceholderText("")
        self.middleName_input.setObjectName("middleName_input")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.middleName_input)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.lastName_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lastName_label.setFont(font)
        self.lastName_label.setObjectName("lastName_label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lastName_label)
        self.lastName_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lastName_input.setFont(font)
        self.lastName_input.setStyleSheet("background-color:#FFFFFF;")
        self.lastName_input.setText("")
        self.lastName_input.setPlaceholderText("")
        self.lastName_input.setObjectName("lastName_input")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lastName_input)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.username_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.username_label)
        self.username_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.username_input.setFont(font)
        self.username_input.setStyleSheet("background-color:#FFFFFF;")
        self.username_input.setText("")
        self.username_input.setPlaceholderText("")
        self.username_input.setObjectName("username_input")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.username_input)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.password_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.password_input.setFont(font)
        self.password_input.setStyleSheet("background-color:#FFFFFF;")
        self.password_input.setText("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setPlaceholderText("")
        self.password_input.setObjectName("password_input")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.password_input)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        self.birthdate_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.birthdate_label.setFont(font)
        self.birthdate_label.setObjectName("birthdate_label")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.birthdate_label)
        self.birthdate_edit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.birthdate_edit.setFont(font)
        self.birthdate_edit.setMouseTracking(False)
        self.birthdate_edit.setStyleSheet("background-color:#FFFFFF;")
        self.birthdate_edit.setCalendarPopup(True)
        self.birthdate_edit.setObjectName("birthdate_edit")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.birthdate_edit)
        self.loa_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.loa_label.setFont(font)
        self.loa_label.setObjectName("loa_label")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.loa_label)
        self.loa_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.loa_input.setFont(font)
        self.loa_input.setStyleSheet("background-color:#FFFFFF;")
        self.loa_input.setReadOnly(True)
        self.loa_input.setPlaceholderText("")
        self.loa_input.setObjectName("loa_input")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.loa_input)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(11, QtWidgets.QFormLayout.FieldRole, spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(13, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.registerButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.registerButton.setFont(font)
        self.registerButton.setStyleSheet("background-color:#53C851;")
        self.registerButton.setDefault(True)
        self.registerButton.setFlat(False)
        self.registerButton.setObjectName("registerButton")
        # Connect the "Register" button to the register_user method
        self.registerButton.clicked.connect(self.register_user)
        self.horizontalLayout.addWidget(self.registerButton)
        self.clearButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        self.clearButton.setFont(font)
        self.clearButton.setStyleSheet("background-color:#E14545;\n"
"")
        self.clearButton.setDefault(True)
        self.clearButton.setObjectName("clearButton")
        # Connect the "Clear" button to the clear_text method
        self.clearButton.clicked.connect(self.clear_text)
        self.horizontalLayout.addWidget(self.clearButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        AdminRegistration.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AdminRegistration)
        self.statusbar.setObjectName("statusbar")
        AdminRegistration.setStatusBar(self.statusbar)

        self.retranslateUi(AdminRegistration)
        QtCore.QMetaObject.connectSlotsByName(AdminRegistration)

    def retranslateUi(self, AdminRegistration):
        _translate = QtCore.QCoreApplication.translate
        AdminRegistration.setWindowTitle(_translate("AdminRegistration", "MainWindow"))
        self.Jewell7.setText(_translate("AdminRegistration", "Jewell 7"))
        self.Hardware.setText(_translate("AdminRegistration", "Hardware"))
        self.firstName_label.setText(_translate("AdminRegistration", "First Name:"))
        self.middleName_label.setText(_translate("AdminRegistration", "Middle Name:"))
        self.lastName_label.setText(_translate("AdminRegistration", "Last Name:"))
        self.username_label.setText(_translate("AdminRegistration", "Username:"))
        self.password_label.setText(_translate("AdminRegistration", "Password:"))
        self.birthdate_label.setText(_translate("AdminRegistration", "Birthdate:"))
        self.loa_label.setText(_translate("AdminRegistration", "LOA:"))
        self.loa_input.setText(_translate("AdminRegistration", "admin"))
        self.registerButton.setText(_translate("AdminRegistration", "Register"))
        self.clearButton.setText(_translate("AdminRegistration", "Clear"))

    def clear_text(self):
        self.firstName_input.clear()
        self.middleName_input.clear()
        self.lastName_input.clear()
        self.username_input.clear()
        self.password_input.clear()
        self.birthdate_edit.setDate(QtCore.QDate.currentDate())

    def register_user(self):
        # Fetching data from input fields
        first_name = self.firstName_input.text().strip()
        middle_name = self.middleName_input.text().strip()
        last_name = self.lastName_input.text().strip()
        username = self.username_input.text().strip()
        password = self.password_input.text().strip()
        birthdate = self.birthdate_edit.date().toString(QtCore.Qt.ISODate)
        loa = self.loa_input.text().strip()

        # Validation: Check if any field is empty
        if not all([first_name, last_name, username, password, birthdate, loa]):
            # Displaying a message box for error
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Warning)
            msg.setText("Please fill in all the fields.")
            msg.setWindowTitle("Error")
            msg.exec_()
            return

        # Get the current date
        current_date = datetime.today()
        # Format the date to ISO 8601 format
        date_started = current_date.strftime('%Y-%m-%d')

        # Establishing connection with SQLite database
        conn = sqlite3.connect('j7h.db')
        cursor = conn.cursor()

        # Inserting data into the users table
        cursor.execute('''INSERT INTO users (first_name, last_name, username, password, loa) 
                          VALUES (?, ?, ?, ?, ?)''', (first_name, last_name, username, password, loa))

        # Retrieve the user_id of the newly inserted user
        user_id = cursor.lastrowid  # This fetches the last inserted row id, which is the user_id

        # Inserting data into the admin table using the retrieved user_id
        cursor.execute('''INSERT INTO admin (first_name, last_name, birthdate, date_started, middle_name, user_id) 
                          VALUES (?, ?, ?, ?, ?, ?)''', (first_name, last_name, birthdate, date_started, middle_name, user_id))

        # Committing the transaction and closing connection
        conn.commit()
        conn.close()

        # Displaying a message box
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setText("User Registered Successfully!")
        msg.setWindowTitle("Success")
        msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminRegistration = QtWidgets.QMainWindow()
    ui = Ui_AdminRegistration()
    ui.setupUi(AdminRegistration)
    AdminRegistration.show()
    sys.exit(app.exec_())
